name: Sync Docker Hub Images to Aliyun and Huawei Cloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo
        sudo apt-get install -y python3-pip
        pip3 install pyyaml
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Login to Aliyun Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUM_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUM_DOCKER_PASSWORD }}
      
    - name: Login to Huawei Cloud Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: swr.cn-southwest-2.myhuaweicloud.com
        username: ${{ secrets.HWYUM_DOCKER_USERNAME }}
        password: ${{ secrets.HWYUM_DOCKER_PASSWORD }}
    
    - name: Sync images
      run: |
        python3 app/sync_images.py
