name: Sync Docker Hub Images to Aliyun and Huawei Cloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Login to Aliyun Container Registry
      run: echo ${{ secrets.ALIYUN_DOCKER_PASSWORD }} | docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin
      
    - name: Login to Huawei Cloud Container Registry
      run: echo ${{ secrets.HUAWEI_DOCKER_PASSWORD }} | docker login -u ${{ secrets.HUAWEI_DOCKER_USERNAME }} swr.cn-north-4.myhuaweicloud.com --password-stdin
    
    - name: 使用 Skopeo 工具同步镜像到 Aliyun
      run: |
         skopeo sync --src docker --dest docker docker.io/llody registry.cn-hangzhou.aliyuncs.com/llody55    
    - name: 使用 Skopeo 工具同步镜像到 华为云
      run: |
         skopeo sync --src docker --dest docker docker.io/llody swr.cn-southwest-2.myhuaweicloud.com/llody55
