name: Sync Docker Hub Images to Aliyun and Huawei Cloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Login to Aliyun Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUM_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUM_DOCKER_PASSWORD }}
      
    - name: Login to Huawei Cloud Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: swr.cn-southwest-2.myhuaweicloud.com
        username: ${{ secrets.HWYUM_DOCKER_USERNAME }}
        password: ${{ secrets.HWYUM_DOCKER_PASSWORD }}
    
    - name: 使用 Skopeo 工具同步镜像到 Aliyun
      run: |
         skopeo sync --src docker --dest docker docker.io/llody registry.cn-hangzhou.aliyuncs.com/llody55    
    - name: 使用 Skopeo 工具同步镜像到 华为云
      run: |
         skopeo sync --src docker --dest docker docker.io/llody swr.cn-southwest-2.myhuaweicloud.com/llody55
